import { Propiedad, Testimonio, MiembroEquipo } from "./types";

export const VALOR_UF_DEFAULT = 39000;

export const propiedades: Propiedad[] = [
  {
    id: "1",
    titulo: "Casa moderna con jardín privado",
    operacion: "venta",
    tipo: "casa",
    precio_uf: 2800,
    precio_clp: 2800 * VALOR_UF_DEFAULT,
    comuna: "Maipú",
    direccion: "Av. Pajaritos, Maipú",
    m2: 110,
    dormitorios: 3,
    banos: 2,
    imagen: "/images/prop1.jpg",
    destacada: true,
    descripcion: "Hermosa casa con jardín privado, cocina americana equipada, estacionamiento cubierto y amplio living.",
  },
  {
    id: "2",
    titulo: "Departamento con terraza panorámica",
    operacion: "venta",
    tipo: "departamento",
    precio_uf: 1950,
    precio_clp: 1950 * VALOR_UF_DEFAULT,
    comuna: "Maipú",
    direccion: "Américo Vespucio Sur, Maipú",
    m2: 68,
    dormitorios: 2,
    banos: 2,
    imagen: "/images/prop2.jpg",
    destacada: true,
    descripcion: "Depto con amplia terraza, vistas despejadas y acceso a piscina, gimnasio y sala multiuso.",
  },
  {
    id: "3",
    titulo: "Casa familiar en condominio cerrado",
    operacion: "venta",
    tipo: "casa",
    precio_uf: 3400,
    precio_clp: 3400 * VALOR_UF_DEFAULT,
    comuna: "Pudahuel",
    direccion: "Sector Balmaceda, Pudahuel",
    m2: 145,
    dormitorios: 4,
    banos: 3,
    imagen: "/images/prop3.jpg",
    destacada: false,
    descripcion: "Amplia casa en condominio con seguridad 24/7, 4 dormitorios, patio trasero y bodega.",
  },
  {
    id: "4",
    titulo: "Departamento amoblado ideal inversión",
    operacion: "arriendo",
    tipo: "departamento",
    precio_uf: 12,
    precio_clp: 12 * VALOR_UF_DEFAULT,
    comuna: "Maipú",
    direccion: "Rinconada de Maipú",
    m2: 42,
    dormitorios: 1,
    banos: 1,
    imagen: "/images/prop4.jpg",
    destacada: true,
    descripcion: "Depto amoblado, segundo piso con luz natural, cocina equipada. Ideal para profesionales.",
  },
  {
    id: "5",
    titulo: "Casa acogedora con amplio patio",
    operacion: "arriendo",
    tipo: "casa",
    precio_uf: 18,
    precio_clp: 18 * VALOR_UF_DEFAULT,
    comuna: "Cerrillos",
    direccion: "Av. Pedro Aguirre Cerda, Cerrillos",
    m2: 80,
    dormitorios: 3,
    banos: 1,
    imagen: "/images/prop5.jpg",
    destacada: false,
    descripcion: "Casa con amplio patio, cerca de colegios y locomoción colectiva. Acepta mascotas.",
  },
  {
    id: "6",
    titulo: "Departamento ejecutivo en Portal Bicentenario",
    operacion: "venta",
    tipo: "departamento",
    precio_uf: 2450,
    precio_clp: 2450 * VALOR_UF_DEFAULT,
    comuna: "Maipú",
    direccion: "Portal Bicentenario, Maipú",
    m2: 82,
    dormitorios: 3,
    banos: 2,
    imagen: "/images/prop6.jpg",
    destacada: true,
    descripcion: "Moderno depto en edificio con piscina, gimnasio, sala eventos y conserje 24/7.",
  },
];

export const testimonios: Testimonio[] = [
  {
    id: "1",
    nombre: "Carolina Rojas M.",
    comuna: "Maipú",
    texto: "Vendí mi casa en menos de tres semanas. El proceso fue 100% digital, sin sorpresas y con comunicación permanente. Quedé muy conforme con el resultado final y la atención recibida.",
    estrellas: 5,
    operacion: "Vendió su casa",
    imagen: "/images/test1.jpg",
  },
  {
    id: "2",
    nombre: "Rodrigo Fuentes P.",
    comuna: "Pudahuel",
    texto: "Me ayudaron a encontrar mi primer depto dentro de mi presupuesto. Explicaron cada etapa de forma clara y sin tecnicismos. Para quienes compran por primera vez, son una excelente opción.",
    estrellas: 5,
    operacion: "Compró su departamento",
    imagen: "/images/test2.jpg",
  },
  {
    id: "3",
    nombre: "Marcela Vargas L.",
    comuna: "Cerrillos",
    texto: "Gestionaron el arriendo de mi propiedad con mucha prolijidad. Encontraron arrendatarios confiables y revisaron toda la documentación. Un servicio realmente profesional.",
    estrellas: 5,
    operacion: "Arrendó su propiedad",
    imagen: "/images/test3.jpg",
  },
  {
    id: "4",
    nombre: "Felipe Morales C.",
    comuna: "Maipú",
    texto: "El simulador hipotecario del sitio me ayudó a entender cuánto podía pedir antes de hablar con el banco. Muy útil y transparente. Los recomiendo sin dudarlo.",
    estrellas: 5,
    operacion: "Compró su casa",
    imagen: "/images/test4.jpg",
  },
];

export const equipo: MiembroEquipo[] = [
  {
    nombre: "Diego Gutiérrez",
    cargo: "Fundador & Corredor Principal",
    descripcion:
      "Con sólida trayectoria en el mercado inmobiliario de Santiago, Diego fundó PropifyConfia con la convicción de que comprar o vender una propiedad debe ser un proceso claro, seguro y al alcance de todos. Su visión digital transformó la forma en que las familias chilenas se conectan con sus propiedades.",
    imagen: "/images/diego.jpg",
  },
  {
    nombre: "Valentina Bustamante",
    cargo: "Ejecutiva Comercial & Experiencia de Cliente",
    descripcion:
      "Valentina es el corazón del equipo. Con vocación de servicio y profundo conocimiento del mercado residencial, acompaña a cada cliente desde la primera consulta hasta la firma del contrato. Su calidez y profesionalismo convierten un proceso complejo en una experiencia tranquila.",
    imagen: "/images/valentina.jpg",
  },
  {
    nombre: "Amaro Gutiérrez",
    cargo: "Asesor Jurídico & Contratos",
    descripcion:
      "Amaro respalda cada operación con rigor legal. Especializado en derecho inmobiliario chileno, revisa contratos, escrituras y condiciones de manera exhaustiva para proteger los intereses de compradores y vendedores por igual. Su trabajo garantiza que cada cierre sea sólido y sin sorpresas.",
    imagen: "/images/amaro.jpg",
  },
];

export const comunas = ["Maipú", "Pudahuel", "Cerrillos", "Cerro Navia", "Lo Espejo", "Estación Central", "Bustos Park"];
